export const UPDATE_SEVERE_TREATMENT = 'UPDATE_SEVERE_TREATMENT';
export const UPDATE_MILD_TREATMENT = 'UPDATE_MILD_TREATMENT';
export const RESET_SEVERE_TREATMENT = 'RESET_SEVERE_TREATMENT';
export const RESET_MILD_TREATMENT = 'RESET_MILD_TREATMENT';
export const SET_SEVERE_CLICKED = 'SET_SEVERE_CLICKED';
export const SET_MILD_CLICKED = 'SET_MILD_CLICKED';
